require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
